let num1 = 12;
let num2 = 31;
console.log(num1);
console.log(num2);
let stringa = "sternocleidomastoiedeo";
console.log(stringa);
stringa = "ribosoma";
console.log(stringa);
const PIGRECO = 3.14159265359;
console.log(PIGRECO);
PIGRECO = 3.14;
console.log(PIGRECO);

let a = 4;
let b = 7;
let c = 5;
let d = 6;
let e = 12;
let sum = ( a + b + c + d + e);
let media = (sum / 5);
console.log(sum);
console.log(media);
let finale = "La somma tra i numeri equivale a "+ sum +" e la media equivale a " + media ;
console.log(finale);

let annocorrente = 2026;
let annodinascita = 1976;
vissuto = annocorrente - annodinascita;
differenzapercentenario = 100 - vissuto;
console.log(vissuto);
console.log(differenzapercentenario);

let a = 12;
let b = 5;
c = a + b;
d = a - b;
e = a * b;
f = a / b;
g = a ** b;
console.log(c);
console.log(d);
console.log(e);
console.log(f);
console.log(g);